# Generated by Django 2.2.5 on 2019-10-02 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import projects.utils.validators
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='IntegrationProject',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Project name')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Project shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Integration project',
                'verbose_name_plural': 'Integration projects',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_ver', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Project version',
            },
        ),
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[projects.utils.validators.validate_name], verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('text', models.TextField(verbose_name='Text')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('audio', models.FileField(null=True, upload_to='records', verbose_name='Record')),
                ('default_audio', models.FileField(null=True, upload_to='records:default-audio', verbose_name='Default record')),
                ('playing_speed', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[projects.utils.validators.validate_speed_accuracy], verbose_name='Speed of the audio')),
                ('emote', models.CharField(choices=[('neutral', 'Neutral'), ('good', 'Good'), ('evil', 'Evil')], max_length=7, null=True)),
                ('related_project', models.ForeignKey(default='MANUAL_EDIT', on_delete=django.db.models.deletion.CASCADE, to='projects.IntegrationProject')),
            ],
            options={
                'verbose_name': 'Audio record',
                'verbose_name_plural': 'Audio records',
                'ordering': ('name', 'text', 'audio', 'modified_at'),
            },
        ),
    ]
