# Generated by Django 2.2.5 on 2019-10-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_manual_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectVersion',
        ),
    ]
