# Generated by Django 2.2.5 on 2019-10-22 10:43

from django.db import migrations, models
import functools
import projects.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_synthesis_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='emote',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='voice',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='audio',
            field=models.FileField(null=True, upload_to=functools.partial(projects.utils.storage.project_path_cb, *(), **{'root': 'records'}), verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='default_audio',
            field=models.FileField(null=True, upload_to=functools.partial(projects.utils.storage.project_path_cb, *(), **{'root': 'records:default-audio'}), verbose_name='Default record'),
        ),
    ]
